In [2]:
import torch

device = 'cuda' if torch.cuda.is_available() else 'cpu'

print('Using {} device'.format(device))

block_size = 8
batch_size = 4

Using cpu device


In [12]:
with open('data/wizard_of_oz.txt', 'r', encoding='utf8') as file:
    text = file.read()
    
chars = sorted(set(text))
print(chars)
vocabulary_size = len(chars)
print(vocabulary_size)

['\n', ' ', '!', '"', '&', "'", '(', ')', '*', ',', '-', '.', '0', '1', '8', '9', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', ']', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
74


In [17]:
string_to_int = { ch:i for i, ch in enumerate(chars) }
int_to_string = { i:ch for i, ch in enumerate(chars) }

encode = lambda s: [string_to_int[ch] for ch in s]
decode = lambda x: ''.join([int_to_string[i] for i in x])

data = torch.tensor(encode(text), dtype=torch.long)

tensor([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 38, 55, 52,  1, 41, 33, 32,
        22, 23, 36, 24, 39, 30,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1, 41, 27, 44, 19, 36, 22,  0,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1])


In [18]:
# Defines the split (80% train, 20% validation)
n = int(0.8 * len(data))
train_data = data[:n]
validation_data = data[n:]

In [19]:
# Defines the block size
block_size = 8

# Defines the input and target data
x = train_data[:block_size]
y = train_data[1:block_size+1]

# Shows the input and target data
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f'when input is {context} target is {target}')
    
# The big difference in performance between CPU and GPU learning is that the CPU has a small number of cores which are very fast, while the GPU has a large number of cores which are slower.

when input is tensor([1]) target is 1
when input is tensor([1, 1]) target is 1
when input is tensor([1, 1, 1]) target is 1
when input is tensor([1, 1, 1, 1]) target is 1
when input is tensor([1, 1, 1, 1, 1]) target is 1
when input is tensor([1, 1, 1, 1, 1, 1]) target is 1
when input is tensor([1, 1, 1, 1, 1, 1, 1]) target is 1
when input is tensor([1, 1, 1, 1, 1, 1, 1, 1]) target is 1


In [21]:
randint = torch.randint(-100, 100, (6,))
print(randint)

tensor([ 74, -90, -45,   2,   5, -58])


In [23]:
tensor = torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [25]:
zeros = torch.zeros(2, 3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [26]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [27]:
inpt = torch.empty(2, 3)
inpt

tensor([[-7.3504e-11,  4.5845e-41, -5.0452e-24],
        [ 4.5846e-41, -7.3507e-11,  4.5845e-41]])

In [28]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [31]:
linspace = torch.linspace(3, 10, steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [32]:
logspace = torch.logspace(start=-10, end=10, steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [33]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [34]:
a = torch.empty((2, 3), dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[3182391460041326592, 7310593858020254331, 3616445622929465956],
        [6068937142572166452, 3833471716613042738, 6499601583586095406]])

In [35]:
import numpy as np
import time

In [49]:
start_time = time.time()

zeros = torch.zeros(4, 4)

end_time = time.time()

elapsed_time = end_time - start_time

print(f'elapsed time: {elapsed_time}')

elapsed time: 0.0001647472381591797


In [51]:
torch_rand1 = torch.rand(10000, 10000).to(device)
torch_rand2 = torch.rand(10000, 10000).to(device)

np_rand1 = np.random.rand(10000, 10000)
np_rand2 = np.random.rand(10000, 10000)

start_time = time.time()

result_torch = (torch_rand1 @ torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f'elapsed time for torch: {elapsed_time}')

start_time = time.time()

result_np = np.multiply(np_rand1, np_rand2)

end_time = time.time()
print(f'elapsed time for numpy: {elapsed_time}')

elapsed time for torch: 0.013355731964111328
elapsed time for numpy: 0.013355731964111328


In [15]:
probabilities = torch.tensor([0.1, 0.9])

samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)

tensor([1, 0, 1, 1, 1, 1, 1, 0, 1, 1])


In [18]:
tensor = torch.tensor([1, 2, 3, 4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
print(out)

tensor([1, 2, 3, 4, 5])


In [17]:
out = torch.tril(torch.ones(5, 5))
print(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])


In [19]:
out = torch.triu(torch.ones(5, 5))
print(out)

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])


In [21]:
out = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5, 5)) == 0, float('-inf'))
print(out)

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])


In [22]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [26]:
inpt = torch.zeros(2, 3, 4)
out = inpt.transpose(0, 2)
print(out.shape)

torch.Size([4, 3, 2])


In [34]:
import torch.nn as nn

sample = torch.tensor([10., 10., 10.])
linear = nn.Linear(3, 3, bias=False)
print(linear(sample))

tensor([-0.3777, -2.8071, -5.1250], grad_fn=<SqueezeBackward4>)


In [1]:
import torch
import torch.nn.functional as F

tensor1 = torch.tensor([1.0, 2.0, 3.0])

softmax_output = F.softmax(tensor1, dim=0)

print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [9]:
# Matrix multiplication
matA = torch.tensor([[2, 3], [1, 2], [3, 4]])
matB = torch.tensor([[1, 2, 3], [5, 6, 7]])

print(matA @ matB)
print(matB @ matA)
print(torch.matmul(matA, matB))

tensor([[17, 22, 27],
        [11, 14, 17],
        [23, 30, 37]])
tensor([[13, 19],
        [37, 55]])
tensor([[17, 22, 27],
        [11, 14, 17],
        [23, 30, 37]])


In [3]:
x = torch.tensor([-0.05], dtype=torch.float32)
y = F.relu(x)

print(y)

tensor([0.])
